Confirmations set the cursor back to the beginning of the line.
Otherwise they get printed in the wrong spot.

````
❯ cargo run --bin but -- -C ~/dev-gb/gitbutler but config forge auth
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/but -C /Users/byron/dev-gb/gitbutler but config forge auth`
? Select a forge provider to authenticate with: GitHub
? Select an authentication method: Device flow (OAuth)
Device authorization initiated. Please visit the following URL and enter the code:

https://github.com/login/device

Code: A438-1C8F

After completing authorization in your browser, press 'y' to continue. [y/n]: y
Error: Authentication failed

Caused by:
    0: Failed to parse response body
    1: missing field `access_token` at line 1 column 208

````

Reviewed-by: Sebastian Thiel <sebastian.thiel@icloud.com>